### PR TITLE
Added a context menu to item view with actions for the individual slot.

### PR DESCRIPTION
**Pull request by CaptainSticky**
This pull request adds a contextmenu to the ItemView component, so that the user can perform actions on an individual equipment slot. These actions include:

1. Open in Console Games Wiki - opens the page for this item on Console Games Wiki
2. Open in Gamer Escape - opens the page for this item on Gamer Escape
3. Open in Garland Tools - opens Garland Tools with the item card.
4. Copy Item Name to Clipboard
5. Reset Slot - resets the slot to the state it was when the actor was pinned, uses the pinned actor's original saved data.
6. Clear Slot

This was requested as part of #1380.

### CODE REVIEW

**Comment by ergoxiv** [comment]
The code itself look good to me. And the context menu options seem to work. I do feel like two things need to be discussed though:

1. Do we want to display these websites' icons? Personally, I feel like it stands out in a bad way and would rather go without them. There's also the question of copyright. Can we use those icons? If there's no public information then I think at the very least we should contact them before using them, not to mention also hosting a copy of their asset in the repo.

2. Some of the items that you can pick in Anamnesis are not valid items (e.g. "Smallclothes (NPC)", "Nothing", "Gleaners Attire", the dated equipmnent, etc.). Trying to open the wiki pages for these will lead to a non-existent page. I think in such circumstances we shouldn't display the context menu option or should at least disable it (i.e. gray it out). Generally speaking, if something can go wrong, then it will definitely go wrong for someone and I think we should try to put safeguards on everything we can.

**Comment by StoiaCode** [comment]
1. No Absolutely not. I get the idea behind it, kinda cute but this just enters deep waters we should just stay out of. 
2. I agree here, though im not sure what would be an easy way to _realiably_ detect this. Keeping a manually maintained option here is not the way to go, and im not sure if there is a conceivable way to get which items do and dont have an entry.

**Comment by CaptainSticky** [comment]
1. Removed the icons. I replaced them with a FA icon instead.
2. I added a property to determine if an item can be opened in one of those sites. In the following cases, it will hide the links:
-- The item is null for some reason.
-- The item has a base of 0, 9901, or 9903, which are small clothes, small clothes npc 2 (feet), and small clothes npc.
-- The item has a rowId of 0, which was the case when I entered an invalid base/variant combination.
-- The item is not in the None, Standard, Premium, Limited category. Items like Forum Attire have the CustomEquipment category.
3. I removed Gleaner's Attire from the special equipment list. They are a valid item... no need to have double.
4. Update ItemCategories.json with some items from the sheets. It would be really nice to know how the previous developer was maintaining this or derived this information.

**Comment by StoiaCode** [comment]
Thank you! That looks like a rather sane implementation of it. 
Also thanks for that update on the Premium and Limited items hahahaha, I dont think anyone actively looked at that for quite literally years. 

Ill test it later today (CEST) and then come back to you.

**Comment by StoiaCode** [comment]
Finally got around. 

I got a crash once: 
`2024-09-13 15:38:53.212 +02:00 [FTL] OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Anamnesis.Actor.Views.ItemView.OnCopyItemNameClicked(Object sender, RoutedEventArgs e) in C:\Users\<name>\Source\Repos\Anamnesis_Upstream\Anamnesis\Actor\Views\ItemView.xaml.cs:line 204
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`
   
 Happend on NPC Smallcloth on the Legs. To me, 100% reproducable. Even then it should probably be cought and handled not leading to a fatal crash hopefully :D

**Comment by CaptainSticky** [comment]
Oh wow, crazy! Did not expect that. I'll dive into it and push a fish.

**Comment by StoiaCode** [comment]
Now you better deliver that Fish.

**Comment by CaptainSticky** [comment]
Since I'm on the **hook** for it, meet Charles:
`      /`·.¸
     /¸...¸`:·
 ¸.·´  ¸   `·.¸.·´)
: © ):´;      ¸  {
 `·.¸ `·  ¸.·´\`·¸)
     `\\´´\¸.·´`

I switched to using the ClipboardUtility Ana already uses elsewhere, and I added a catch just in case it does eventually throw after the 3 attempts. Clipboard.SetText will throw if it fails to open the Clipboard, for example if it's in-use or blocked. The existing ClipboardUtility will try 3 times. I also changed it to not run infinitely, as it wasn't decrementing its counter. 

I tried copying the same item repeatedly for about 15m straight and the most it needed was a second attempt and only in about 1/5 times.

I also added a bool to not show the copy option if there's no item.

**Pull request merged**
