### PR TITLE
Updated offsets for hat visibility and visor/weapon drawn/visible flags.

### PR DESCRIPTION
**Pull request by CaptainSticky**
This pull request updates two offsets. The first is for the hat visibility toggle, and the second is for characters flags which relate to weapon visibility/drawn and visor state. Math was done.

### CODE REVIEW

**Comment by ergoxiv** [comment]
Yeah, these are the correct offsets but the hat toggle doesn't seem to work properly. It gets written to by the button'w data binding and then the value flips back to it's old state after WriteDelayedBinds() gets called.

**Comment by CaptainSticky** [comment]
I can't seem to get this to happen for me. I've turned off both Brio and Penumbra integration and log'd out when WriteDelayedBinds is done. It seemed okay when I toggled it both from the game and from Ana. How did you get this behavior?

**Comment by ergoxiv** [comment]
Toggling visibility through Anamnesis' equipment editor. I tried both with and without integration but for me this issue occurs on both. If it's only me then it might be Glamourer causing issues though I was under the impression I had it disabled. I'll check once I get home.

**Comment by CaptainSticky** [comment]
Oooh! I think it's because I don't use Glamourer. I installed it and was able to reproduce the issue... and strangely, only with that one thing. The same issue occurs with both Brio and Ktisis.

**Comment by StoiaCode** [comment]
That's to be expected. Glamourer needs to be disabled in order for Anamnesis to work properly. The two are inherently editing two different parts of memory that when brought into disharmony will fight over who is correct.

**Comment by StoiaCode** [comment]
Just got to test aroudn, im curious now what was broken with the Weapons? Im probably missing something, but the draw weapon and visibility toggle both work to me in current Ana, no?

**Comment by CaptainSticky** [comment]
The byte that Ana uses to control whether the weapon (main hand only it seems?) is on the weapon memory. However, the byte used for toggling visor state also, according to the existing code and client structs, has visibility into the weapon state (visibility and being drawn.) In short, this change shouldn't affect those these, since the two character flags bytes are only being affected for hat visibility and visor state.

I do want to look into the off hand not being hidden though at some point... that appears to be an issue in the current Ana as well.

**Pull request merged**
